name: control-smart

on:
  repository_dispatch:
    types: [solar_on, solar_off]

jobs:
  control_device:
    runs-on: ubuntu-latest

    env:
      SMARTTHINGS_TOKEN: ${{ secrets.SMARTTHINGS_TOKEN }}

    steps:
      - name: เปิด FillPump เมื่อ solar_on
        if: github.event.action == 'solar_on'
        run: |
          echo "🔛 เปิด FillPump ผ่าน SmartThings"
          curl -X POST "https://api.smartthings.com/v1/devices/74b5a597-3444-4f9d-b879-cca0de01c7ad/commands" \
            -H "Authorization: Bearer $SMARTTHINGS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
                  "commands": [
                    {
                      "component": "main",
                      "capability": "switch",
                      "command": "on"
                    }
                  ]
                }'

      - name: ปิด FillPump เมื่อ solar_off
        if: github.event.action == 'solar_off'
        run: |
          echo "🔻 ปิด FillPump ผ่าน SmartThings"
          curl -X POST "https://api.smartthings.com/v1/devices/74b5a597-3444-4f9d-b879-cca0de01c7ad/commands" \
            -H "Authorization: Bearer $SMARTTHINGS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
                  "commands": [
                    {
                      "component": "main",
                      "capability": "switch",
                      "command": "off"
                    }
                  ]
                }'
