name: ewelink-control

on:
  repository_dispatch:
    types: [solar_on, solar_off]

jobs:
  send_to_ifttt:
    runs-on: ubuntu-latest

    steps:
      - name: ตั้งค่า EVENT_TYPE
        run: echo "EVENT_TYPE=${{ github.event.action }}" >> $GITHUB_ENV

      - name: ส่งข้อมูลไปยัง Google Form ตามคำสั่ง
        run: |
          if [ "$EVENT_TYPE" = "solar_on" ]; then
            curl -X POST https://docs.google.com/forms/d/e/1FAIpQLSdf_K9EN_B9CEMTtxbyQ8K5R8n1z3f3956wFQk9Jm5n2dK3Wg/formResponse \
              -d "entry.1457809611=on"
          fi

          if [ "$EVENT_TYPE" = "solar_off" ]; then
            curl -X POST https://docs.google.com/forms/d/e/1FAIpQLSdf_K9EN_B9CEMTtxbyQ8K5R8n1z3f3956wFQk9Jm5n2dK3Wg/formResponse \
              -d "entry.1457809611=off"
          fi
