name: log-to-line

on:
  repository_dispatch:
    types: [log_event]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: แจ้งเตือนผ่าน LINE ผ่าน Webhook
        run: |
          curl -X POST https://eo2jv7jv7xq3z7z.m.pipedream.net \
            -d "soc=${{ github.event.client_payload.soc }}&event=${{ github.event.client_payload.event_type }}"
