name: log-to-line

on:
  workflow_dispatch:
    inputs:
      soc:
        description: 'Battery SOC (%)'
        required: true
        default: '23'
      event_type:
        description: 'Event type (e.g. Low Batt, Normal Batt)'
        required: true
        default: 'Low Batt'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: แจ้งเตือนผ่าน LINE ผ่าน Webhook
        run: |
          curl -X POST https://eo2jv7jv7xq3z7z.m.pipedream.net \
            -d "soc=${{ inputs.soc }}&event=${{ inputs.event_type }}"

      - name: Log Success
        if: ${{ success() }}
        run: |
          echo "✅ แจ้งเตือนสำเร็จ: SOC=${{ inputs.soc }}%, สถานะ=${{ inputs.event_type }}"

      - name: Log Failure
        if: ${{ failure() }}
        run: |
          echo "❌ แจ้งเตือนไม่สำเร็จ: ตรวจสอบ webhook หรือค่า input"
