name: send-to-form-b

on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: ส่งข้อมูลไปยัง Google Form B
        run: |
          curl -X POST https://docs.google.com/forms/d/e/1FAIpQLSdGHk7v1b9RX2GeKl0w_BSDcmTtbxtyK0F3595fcpqQagLxEQ/formResponse \
            -d "entry.1686318127=solar_off" \
            -d "entry.1457056019=ESP"

