name: Manual Submit to Google Form

on:
  workflow_dispatch:
    inputs:
      event_type:
        description: 'Event type to send'
        required: true
        default: 'solar_on'

jobs:
  submit-form:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Google Form
        run: |
          curl -X POST "https://docs.google.com/forms/d/e/1FAIpQLSc9asPeR_xC3-stBX1OrMKx_rmYBDOL-rhx4mep71EvdktKgg/formResponse?entry.1131282568=${{ github.event.inputs.event_type }}&entry.1829867408=GitHub"
