name: send-to-on
on:
  repository_dispatch:
    types: [solar_on]
jobs:
  log_event:
    runs-on: ubuntu-latest
    steps:
      - name: ส่งไป Google Form ON
        run: |
          curl -X POST https://docs.google.com/forms/d/e/1FAIpQLSchglVNdUfC_titEV191XeR_uH9NnVYyMMmtuoZmgM0oH3yVg/formResponse \
            -d "entry.29631913=solar_on" \
            --fail --silent --show-error
