name: log-to-google-form
on:
  repository_dispatch:
    types: [log_event]  # ตรงกับ event_type ที่ ESP32 ส่งมา
jobs:
  log_event:
    runs-on: ubuntu-latest
    steps:
      # ส่งข้อมูลไป Google Form
      - name: ส่งข้อมูลจาก ESP ไปยัง Google Form
        run: |
          curl -X POST https://docs.google.com/forms/d/e/1FAIpQLSdrDVFEEkkdZ6k4rdG4OCkTWoek9GBk1Uip-GWWDZR8HCsXkQ/formResponse \
            -d "entry.747932621=${{ github.event.client_payload.soc }}" \
            -d "entry.1561980421=${{ github.event.client_payload.status }}" \
            --fail --silent --show-error
